export const taxCalculatorEn = {
	meta:{title:'Free Employee Cost Calculator: Estimate the True Cost of Hiring Globally | Garna',description:'Know the true cost of hiring with Garna’s free Global Employee Cost Calculator. Estimate employment expenses and employee deductions for global teams.'},
	hero:{badge:'Global salary intelligence',title:'Employee Cost Calculator',description:'Salary is only part of the equation. Estimate take-home pay, statutory deductions and annual net income in seconds, with no sign-up required.',calculateCta:'Calculate Employment Cost',demoCta:'Request a Demo',countries:'supported countries',updated:'Current tax logic'},
	calculator:{eyebrow:'Employee cost calculator',title:'Calculate net salary and deductions',live:'Live estimate',country:'Country',selectCountry:'Select a country',state:'State or region',salary:'Gross salary',period:'Pay period',monthly:'Monthly',annual:'Annual',currency:'Currency',calculate:'Calculate Employment Cost'},
	info:{kicker:'Understand the full picture',title:'From gross offer to money in your employee’s account',grossTitle:'Enter gross salary',grossText:'Choose the location, pay period and offer currency.',taxTitle:'Apply local deductions',taxText:'The estimate accounts for country and regional tax logic.',netTitle:'Review take-home pay',netText:'See annual net income and a transparent deduction breakdown.'},
	trusted:{kicker:'Trusted by Businesses Scaling Globally',countries:'countries supported by Garna',platform:'One platform for global payroll and compliance'},expert:{kicker:'Questions about your report?',title:'Our global hiring experts can help.',text:'Understand your costs and explore the best hiring options for your international team.',cta:'Talk to an Expert'},
	messages:{loading:'Calculating…',configError:'Could not load country details. Please try again.',calcError:'Could not calculate right now. Please try again.'},results:{gross:'Gross annual',net:'Net annual',deductions:'Taxes and deductions',item:'Item',estimate:'Your estimated employee cost',estimatedNote:'This result is an estimate based on local taxation and standard employment requirements. Final amounts may vary based on employee-specific details and company policies.',garnaSupports:'Garna supports payroll operations in',garnaText:'Garna helps you hire and pay employees in 150+ countries without establishing your own local entity.',onboard:'Onboard Employee'},
	faq:{title:'Employee Cost Calculator FAQs',q1:'What is an employee cost calculator?',a1:'An employee cost calculator is a tool that helps businesses estimate the cost of hiring an employee. It considers salary and employment-related expenses such as taxes, social contributions, benefits and other required costs.',q2:'How do you calculate the total cost of an employee?',a2:'Start with gross salary, then add applicable employer taxes, benefits and additional employment costs. The exact total depends on the employee’s location, employment type, industry and benefits package.',q3:'How much does an employee cost a company beyond salary?',a3:'The additional cost depends on the country and benefits offered. In many markets employers pay taxes, insurance, social contributions and benefits on top of gross salary.',q4:'Does employee cost vary by country?',a4:'Yes. Payroll taxes, social security contributions, mandatory benefits, healthcare systems and employment regulations differ significantly between countries.',q5:'What is the difference between salary and total employee cost?',a5:'Salary is the compensation paid directly to an employee. Total employee cost includes salary plus taxes, benefits and other expenses the employer pays to maintain employment.',q6:'How can I reduce employee hiring costs?',a6:'Businesses can automate payroll, choose the right employment model, optimize benefits, hire in suitable markets and use global payroll solutions to reduce administrative overhead.',q7:'How do I calculate the cost of hiring an employee internationally?',a7:'Consider salary expectations, local payroll taxes, employer contributions, mandatory benefits, exchange rates and compliance requirements before expanding into a new market.',q8:'Can Garna help manage employee payroll costs?',a8:'Yes. Garna helps businesses manage global payroll, employee payments and compliance across multiple countries through one platform.',q9:'How accurate are employee cost calculator estimates?',a9:'Results are estimates based on available tax rates, contributions and typical employment requirements. Actual amounts may vary according to employee details, company policies and local regulations.'}
};
