name = "garna-io"
main = "src/index.ts"
account_id = "f67149c49bb3df8b37eb59f539a72c97"
compatibility_date = "2024-12-01"

[dev]
port = 8788

[vars]
USE_STATIC_ASSETS = "true"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [
	"/",
	"/index.html",
	"/for-contractors",
	"/for-contractors.html",
	"/form",
	"/form.html",
	"/ai-hiring",
	"/ai-hiring.html",
	"/white-label",
	"/white-label.html",
	"/payroll-small-business",
	"/payroll-small-business.html",
	"/eor",
	"/eor.html",
]
