name = "garna-io"
main = "src/index.ts"
account_id = "f67149c49bb3df8b37eb59f539a72c97"
compatibility_date = "2024-12-01"

[dev]
port = 8788

[vars]
USE_STATIC_ASSETS = "true"
PUBLIC_ORIGIN = "https://garna.io"
EMAIL_FROM = "noreply@garna.io"
ADMIN_EMAILS = "info@mediacube.network,sol@mediacube.io,angelm@mediacube.io,dariab@mediacube.io"

[[d1_databases]]
binding = "DB"
database_name = "garna-blog"
database_id = "e76ba814-904b-4a34-b6ff-51f601b3a5ad"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "BLOG_MEDIA"
bucket_name = "garna-blog-media"

[[send_email]]
name = "EMAIL"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = [
	"/",
	"/index.html",
	"/for-contractors",
	"/for-contractors.html",
	"/form",
	"/form.html",
	"/ai-hiring",
	"/ai-hiring.html",
	"/white-label",
	"/white-label.html",
	"/payroll-small-business",
	"/payroll-small-business.html",
	"/eor",
	"/eor.html",
	"/blog",
	"/blog.html",
	"/en/blog",
	"/ru/blog",
	"/es/blog",
	"/pt/blog",
	"/blog-author",
	"/blog-author.html",
	"/en/blog-author",
	"/ru/blog-author",
	"/es/blog-author",
	"/pt/blog-author",
	"/blog-article",
	"/blog-article.html",
	"/en/blog-article",
	"/ru/blog-article",
	"/es/blog-article",
	"/pt/blog-article",
]
