import type { PageShellConfig } from '../types/page-shell';

export const pageShells = {
	gamescom2026: {
		title: 'Gamescom 2026 Side Events Guide | Cologne, 23–30 August | Garna',
		description: 'Gamescom 2026 side events in Cologne, 23–30 August: mixers, dinners, pitch sessions and parties, with how to get into each one. Kept up to date by Garna.',
		keywords: 'Gamescom 2026, Gamescom side events, Cologne events, gaming events, Garna',
		ogImage: '/pages/payroll-solution-new/assets/04-d53eeb9d-92c5-4820-9733-4fe2e036e76e_800w.png',
		htmlClass: 'scroll-smooth',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-[#CBF300] selection:text-black bg-garna-page',
		iconLibrary: 'lucide',
	},
	eorCostCalculator: {
		title: 'EOR Cost Calculator: Compare Employer of Record Fees | Garna',
		description: 'Compare your current Employer of Record service fee with Garna and estimate annual EOR savings, salary and employer contributions.',
		keywords: 'EOR cost calculator, employer of record cost, EOR fees, EOR comparison, Garna',
		htmlClass: 'scroll-smooth dark',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-[#CBF300]/40 selection:text-white bg-garna-page',
		iconLibrary: 'lucide',
	},
	taxCalculator: {
		title: 'Free Employee Cost Calculator: Estimate the True Cost of Hiring Globally | Garna',
		description: 'Know the true cost of hiring with Garna’s free Global Employee Cost Calculator. Estimate total employment expenses for global teams.',
		keywords: 'employee cost calculator, employment cost calculator, global hiring cost, salary tax calculator, Garna',
		htmlClass: 'scroll-smooth dark',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-[#CBF300]/40 selection:text-white bg-garna-page',
		iconLibrary: 'lucide',
	},
	contractorOfRecord: {
		"title": "Global Payroll and Payments in 150+ Countries | Garna",
		"description": "Reliable payroll software for international businesses. Automate international payroll, taxes, and compliance. Make fast payments to your team in any currency or cryptocurrency.",
		"keywords": "global payroll, contractor payments, international payroll, Garna, fintech, cross-border payments, payroll solutions",
		"ogImage": "https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png",
		"htmlClass": "scroll-smooth",
		"bodyClass": "antialiased selection:bg-[#CBF300] selection:text-black overflow-x-hidden z-10 text-gray-300 bg-garna-page",
		"iconLibrary": "lucide",
	},
	home: {
		title: 'Global Payroll and Payments in 150+ Countries | Garna',
		description:
			'Reliable payroll software for international businesses. Automate international payroll, taxes, and compliance. Make fast payments to your team in any currency or cryptocurrency.',
		keywords:
			'global payroll solution, international payroll, contractor payments, employer of record, Garna',
		ogImage: '/pages/payroll-solution-new/assets/04-d53eeb9d-92c5-4820-9733-4fe2e036e76e_800w.png',
		htmlClass: 'scroll-smooth dark',
		bodyClass:
			'antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 relative bg-garna-page',
		iconLibrary: 'iconify',
	},
	offer: {
		"title": "Garna for Contractors - Get Paid Globally",
		"description": "Receive payments from clients worldwide with transparent fees and instant withdrawals.",
		"keywords": "contractor payments, get paid globally, freelancer payouts, Garna, international payments, contractor payouts",
		"ogImage": "https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png",
		"htmlClass": "scroll-smooth",
		"bodyClass": "antialiased selection:bg-[#CBF300] selection:text-black overflow-x-hidden text-gray-300 bg-garna-page z-10",
		"iconLibrary": "iconify",
	},
	aiHiring: {
		"title": "Garna - AI Recruitment Platform",
		"description": "Skip the pre-screens. Hire proven talent instantly with AI-powered recruitment and verified candidate reports.",
		"keywords": "AI recruitment, hire talent, AI hiring, candidate screening, Garna, recruitment platform",
		"ogImage": "https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png",
		"htmlClass": "scroll-smooth",
		"bodyClass": "antialiased selection:bg-[#CBF300] selection:text-black overflow-x-hidden text-gray-300 bg-garna-page z-10 relative",
		"iconLibrary": "iconify",
	},
	whiteLabel: {
		"title": "White Label Payroll & Contractor Payments Platform | Garna",
		"description": "Launch global contractor onboarding, management, and payments under your brand with Garna’s white label infrastructure.",
		"keywords": "white label payroll, contractor management, contractor of record, global contractor payments, international payroll, Garna, compliance automation, payroll infrastructure",
		"ogImage": "https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png",
		"htmlClass": "dark",
		"bodyClass": "antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 relative",
		"iconLibrary": "iconify",
	},
	payrollSmallBusiness: {
		title: 'Payroll for Small Business | Garna',
		description:
			'Hire employees, pay contractors, automate taxes, contracts, and bulk payments for small businesses in one Garna payroll platform.',
		keywords:
			'small business payroll, global payroll, payroll for small business, employer of record, contractor payments, Garna',
		ogImage: 'https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png',
		htmlClass: 'scroll-smooth',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-[#CBF300]/30 selection:text-white bg-garna-page',
		iconLibrary: 'iconify',
	},
	eor: {
		"title": "Employer of Record: Remote, Effortless & Effective | Garna",
		"description": "Join Garna and experience how a refined remote employment solution can optimize and simplify hiring talents globally.",
		"keywords": "employer of record, EOR, global employment, international hiring, global payroll, compliance, Garna",
		"ogImage": "https://cdn.prod.website-files.com/690b359fa4596a165b817850/691c82150090fae9b2280e93_Frame%201618873305.png",
		"htmlClass": "scroll-smooth dark",
		"bodyClass": "antialiased overflow-x-hidden selection:bg-[#CBF300]/40 selection:text-white bg-garna-page",
		"iconLibrary": "iconify",
	},
	blog: {
		title: 'Garna Insights Hub',
		description:
			'Expert insights on global hiring, payroll, workforce management, practical guides, industry trends, and international employment updates.',
		keywords: 'Garna blog, global hiring, payroll insights, workforce management, international employment',
		ogImage: '/pages/blog/assets/01-1e96bbb7-a5c7-4597-987a-3a820daffbff_3840w.jpg',
		htmlClass: 'scroll-smooth dark',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 relative bg-garna-page',
		iconLibrary: 'iconify',
	},
	blogAuthor: {
		title: 'Garna Blog Author',
		description: 'Author profile and articles from the Garna Insights Hub.',
		keywords: 'Garna blog author, payroll articles, workforce insights',
		ogImage: '/pages/blog/assets/12-photo-1438761681033-6461ffad8d80.jpg',
		htmlClass: 'scroll-smooth dark',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 relative bg-garna-page',
		iconLibrary: 'iconify',
	},
	blogArticle: {
		title: 'Garna Blog Article',
		description: 'Article page from the Garna Insights Hub.',
		keywords: 'Garna blog article, payroll, workforce management, global hiring',
		ogImage: '/pages/blog/assets/11-fdb0cbaa-87f1-425d-b6a2-ad16a6de7cb7_3840w.jpg',
		htmlClass: 'scroll-smooth dark',
		bodyClass: 'antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 relative bg-garna-page',
		iconLibrary: 'iconify',
	},
	form: {
		"title": "Garna - AI Recruitment Platform",
		"description": "",
		"keywords": "",
		"ogImage": "",
		"htmlClass": "dark",
		"bodyClass": "antialiased overflow-x-hidden selection:bg-indigo-500/30 selection:text-indigo-200 font-manrope relative",
		"iconLibrary": "iconify",
	},
} satisfies Record<string, PageShellConfig>;
