// Countries configuration - Official ISO 3166-1 alpha-2 codes only
export const countries = [
	{
		label: '🇦🇩 Andorra',
		value: 'AD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇪 United Arab Emirates',
		value: 'AE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇫 Afghanistan',
		value: 'AF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇬 Antigua and Barbuda',
		value: 'AG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇮 Anguilla',
		value: 'AI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇱 Albania',
		value: 'AL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇲 Armenia',
		value: 'AM',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇦🇴 Angola',
		value: 'AO',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇦🇶 Antarctica',
		value: 'AQ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇷 Argentina',
		value: 'AR',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇦🇸 American Samoa',
		value: 'AS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇹 Austria',
		value: 'AT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇺 Australia',
		value: 'AU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇼 Aruba',
		value: 'AW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇽 Åland Islands',
		value: 'AX',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇦🇿 Azerbaijan',
		value: 'AZ',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇧🇦 Bosnia and Herzegovina',
		value: 'BA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇧 Barbados',
		value: 'BB',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇩 Bangladesh',
		value: 'BD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇪 Belgium',
		value: 'BE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇫 Burkina Faso',
		value: 'BF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇬 Bulgaria',
		value: 'BG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇭 Bahrain',
		value: 'BH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇮 Burundi',
		value: 'BI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇯 Benin',
		value: 'BJ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇱 Saint Barthélemy',
		value: 'BL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇲 Bermuda',
		value: 'BM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇳 Brunei',
		value: 'BN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇴 Bolivia',
		value: 'BO',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇧🇶 Caribbean Netherlands',
		value: 'BQ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇷 Brazil',
		value: 'BR',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇧🇸 Bahamas',
		value: 'BS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇹 Bhutan',
		value: 'BT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇻 Bouvet Island',
		value: 'BV',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇼 Botswana',
		value: 'BW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇧🇾 Belarus',
		value: 'BY',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇧🇿 Belize',
		value: 'BZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇦 Canada',
		value: 'CA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇨 Cocos Islands',
		value: 'CC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇩 Democratic Republic of the Congo',
		value: 'CD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇫 Central African Republic',
		value: 'CF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇬 Republic of the Congo',
		value: 'CG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇭 Switzerland',
		value: 'CH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: "🇨🇮 Côte d'Ivoire",
		value: 'CI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇰 Cook Islands',
		value: 'CK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇱 Chile',
		value: 'CL',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇨🇲 Cameroon',
		value: 'CM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇳 China',
		value: 'CN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇴 Colombia',
		value: 'CO',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇨🇷 Costa Rica',
		value: 'CR',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇨🇺 Cuba',
		value: 'CU',
		defaultLanguage: 'es',
		otherLanguages: [],
	},
	{
		label: '🇨🇻 Cape Verde',
		value: 'CV',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇼 Curaçao',
		value: 'CW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇽 Christmas Island',
		value: 'CX',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇾 Cyprus',
		value: 'CY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇨🇿 Czech Republic',
		value: 'CZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇩🇪 Germany',
		value: 'DE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇩🇯 Djibouti',
		value: 'DJ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇩🇰 Denmark',
		value: 'DK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇩🇲 Dominica',
		value: 'DM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇩🇴 Dominican Republic',
		value: 'DO',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇩🇿 Algeria',
		value: 'DZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇪🇨 Ecuador',
		value: 'EC',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇪🇪 Estonia',
		value: 'EE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇪🇬 Egypt',
		value: 'EG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇪🇭 Western Sahara',
		value: 'EH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇪🇷 Eritrea',
		value: 'ER',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇪🇸 Spain',
		value: 'ES',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇪🇹 Ethiopia',
		value: 'ET',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇮 Finland',
		value: 'FI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇯 Fiji',
		value: 'FJ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇰 Falkland Islands',
		value: 'FK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇲 Micronesia',
		value: 'FM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇴 Faroe Islands',
		value: 'FO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇫🇷 France',
		value: 'FR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇦 Gabon',
		value: 'GA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇧 United Kingdom',
		value: 'GB',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇩 Grenada',
		value: 'GD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇪 Georgia',
		value: 'GE',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇬🇫 French Guiana',
		value: 'GF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇬 Guernsey',
		value: 'GG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇭 Ghana',
		value: 'GH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇮 Gibraltar',
		value: 'GI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇱 Greenland',
		value: 'GL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇲 Gambia',
		value: 'GM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇳 Guinea',
		value: 'GN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇵 Guadeloupe',
		value: 'GP',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇶 Equatorial Guinea',
		value: 'GQ',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇬🇷 Greece',
		value: 'GR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇸 South Georgia and the South Sandwich Islands',
		value: 'GS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇹 Guatemala',
		value: 'GT',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇬🇺 Guam',
		value: 'GU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇬🇼 Guinea-Bissau',
		value: 'GW',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇬🇾 Guyana',
		value: 'GY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇭🇰 Hong Kong',
		value: 'HK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇭🇲 Heard Island and McDonald Islands',
		value: 'HM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇭🇳 Honduras',
		value: 'HN',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇭🇷 Croatia',
		value: 'HR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇭🇹 Haiti',
		value: 'HT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇭🇺 Hungary',
		value: 'HU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇩 Indonesia',
		value: 'ID',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇪 Ireland',
		value: 'IE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇱 Israel',
		value: 'IL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇲 Isle of Man',
		value: 'IM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇳 India',
		value: 'IN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇴 British Indian Ocean Territory',
		value: 'IO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇶 Iraq',
		value: 'IQ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇷 Iran',
		value: 'IR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇸 Iceland',
		value: 'IS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇮🇹 Italy',
		value: 'IT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇯🇪 Jersey',
		value: 'JE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇯🇲 Jamaica',
		value: 'JM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇯🇴 Jordan',
		value: 'JO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇯🇵 Japan',
		value: 'JP',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇪 Kenya',
		value: 'KE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇬 Kyrgyzstan',
		value: 'KG',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇰🇭 Cambodia',
		value: 'KH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇮 Kiribati',
		value: 'KI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇲 Comoros',
		value: 'KM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇳 Saint Kitts and Nevis',
		value: 'KN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇵 North Korea',
		value: 'KP',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇷 South Korea',
		value: 'KR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇼 Kuwait',
		value: 'KW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇾 Cayman Islands',
		value: 'KY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇰🇿 Kazakhstan',
		value: 'KZ',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇱🇦 Laos',
		value: 'LA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇧 Lebanon',
		value: 'LB',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇨 Saint Lucia',
		value: 'LC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇮 Liechtenstein',
		value: 'LI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇰 Sri Lanka',
		value: 'LK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇷 Liberia',
		value: 'LR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇸 Lesotho',
		value: 'LS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇹 Lithuania',
		value: 'LT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇺 Luxembourg',
		value: 'LU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇻 Latvia',
		value: 'LV',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇱🇾 Libya',
		value: 'LY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇦 Morocco',
		value: 'MA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇨 Monaco',
		value: 'MC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇩 Moldova',
		value: 'MD',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇲🇪 Montenegro',
		value: 'ME',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇫 Saint Martin',
		value: 'MF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇬 Madagascar',
		value: 'MG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇭 Marshall Islands',
		value: 'MH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇰 North Macedonia',
		value: 'MK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇱 Mali',
		value: 'ML',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇲 Myanmar',
		value: 'MM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇳 Mongolia',
		value: 'MN',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇲🇴 Macao',
		value: 'MO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇵 Northern Mariana Islands',
		value: 'MP',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇶 Martinique',
		value: 'MQ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇷 Mauritania',
		value: 'MR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇸 Montserrat',
		value: 'MS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇹 Malta',
		value: 'MT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇺 Mauritius',
		value: 'MU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇻 Maldives',
		value: 'MV',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇼 Malawi',
		value: 'MW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇽 Mexico',
		value: 'MX',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇲🇾 Malaysia',
		value: 'MY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇲🇿 Mozambique',
		value: 'MZ',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇳🇦 Namibia',
		value: 'NA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇨 New Caledonia',
		value: 'NC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇪 Niger',
		value: 'NE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇫 Norfolk Island',
		value: 'NF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇬 Nigeria',
		value: 'NG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇮 Nicaragua',
		value: 'NI',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇳🇱 Netherlands',
		value: 'NL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇴 Norway',
		value: 'NO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇵 Nepal',
		value: 'NP',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇷 Nauru',
		value: 'NR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇺 Niue',
		value: 'NU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇳🇿 New Zealand',
		value: 'NZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇴🇲 Oman',
		value: 'OM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇦 Panama',
		value: 'PA',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇵🇪 Peru',
		value: 'PE',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇵🇫 French Polynesia',
		value: 'PF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇬 Papua New Guinea',
		value: 'PG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇭 Philippines',
		value: 'PH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇰 Pakistan',
		value: 'PK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇱 Poland',
		value: 'PL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇲 Saint Pierre and Miquelon',
		value: 'PM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇳 Pitcairn Islands',
		value: 'PN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇷 Puerto Rico',
		value: 'PR',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇵🇸 Palestine',
		value: 'PS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇹 Portugal',
		value: 'PT',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇵🇼 Palau',
		value: 'PW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇵🇾 Paraguay',
		value: 'PY',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇶🇦 Qatar',
		value: 'QA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇷🇪 Réunion',
		value: 'RE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇷🇴 Romania',
		value: 'RO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇷🇸 Serbia',
		value: 'RS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇷🇺 Russia',
		value: 'RU',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇷🇼 Rwanda',
		value: 'RW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇦 Saudi Arabia',
		value: 'SA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇧 Solomon Islands',
		value: 'SB',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇨 Seychelles',
		value: 'SC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇩 Sudan',
		value: 'SD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇪 Sweden',
		value: 'SE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇬 Singapore',
		value: 'SG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇭 Saint Helena',
		value: 'SH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇮 Slovenia',
		value: 'SI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇯 Svalbard and Jan Mayen',
		value: 'SJ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇰 Slovakia',
		value: 'SK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇱 Sierra Leone',
		value: 'SL',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇲 San Marino',
		value: 'SM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇳 Senegal',
		value: 'SN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇴 Somalia',
		value: 'SO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇷 Suriname',
		value: 'SR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇸 South Sudan',
		value: 'SS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇹 São Tomé and Príncipe',
		value: 'ST',
		defaultLanguage: 'pt',
		otherLanguages: [],
	},
	{
		label: '🇸🇻 El Salvador',
		value: 'SV',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇸🇽 Sint Maarten',
		value: 'SX',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇾 Syria',
		value: 'SY',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇸🇿 Eswatini',
		value: 'SZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇨 Turks and Caicos Islands',
		value: 'TC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇩 Chad',
		value: 'TD',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇫 French Southern Territories',
		value: 'TF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇬 Togo',
		value: 'TG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇭 Thailand',
		value: 'TH',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇯 Tajikistan',
		value: 'TJ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇰 Tokelau',
		value: 'TK',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇱 Timor-Leste',
		value: 'TL',
		defaultLanguage: 'pt',
		otherLanguages: ['en'],
	},
	{
		label: '🇹🇲 Turkmenistan',
		value: 'TM',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇹🇳 Tunisia',
		value: 'TN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇴 Tonga',
		value: 'TO',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇷 Turkey',
		value: 'TR',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇹 Trinidad and Tobago',
		value: 'TT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇻 Tuvalu',
		value: 'TV',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇼 Taiwan',
		value: 'TW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇹🇿 Tanzania',
		value: 'TZ',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇺🇦 Ukraine',
		value: 'UA',
		defaultLanguage: 'en',
		otherLanguages: ['ru'],
	},
	{
		label: '🇺🇬 Uganda',
		value: 'UG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇺🇲 U.S. Minor Outlying Islands',
		value: 'UM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇺🇸 United States',
		value: 'US',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇺🇾 Uruguay',
		value: 'UY',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇺🇿 Uzbekistan',
		value: 'UZ',
		defaultLanguage: 'ru',
		otherLanguages: ['en'],
	},
	{
		label: '🇻🇦 Vatican City',
		value: 'VA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇻🇨 Saint Vincent and the Grenadines',
		value: 'VC',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇻🇪 Venezuela',
		value: 'VE',
		defaultLanguage: 'es',
		otherLanguages: ['en'],
	},
	{
		label: '🇻🇬 British Virgin Islands',
		value: 'VG',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇻🇮 U.S. Virgin Islands',
		value: 'VI',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇻🇳 Vietnam',
		value: 'VN',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇻🇺 Vanuatu',
		value: 'VU',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇼🇫 Wallis and Futuna',
		value: 'WF',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇼🇸 Samoa',
		value: 'WS',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇾🇪 Yemen',
		value: 'YE',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇾🇹 Mayotte',
		value: 'YT',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇿🇦 South Africa',
		value: 'ZA',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇿🇲 Zambia',
		value: 'ZM',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
	{
		label: '🇿🇼 Zimbabwe',
		value: 'ZW',
		defaultLanguage: 'en',
		otherLanguages: [],
	},
];
