import { PRIVACY_COOKIE_NAME, PRIVACY_POLICY_VERSION, deferConsentManagedEmbeds } from './privacy';

const PRIVACY_MARKER = 'data-garna-privacy';

function safeJson(value: unknown): string {
	return JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
}

const PRIVACY_CSS = `<style data-garna-privacy-style>
:root{--gp-lime:#cbf300;--gp-ink:#f7f8f2;--gp-muted:#a5a79f;--gp-panel:#10110f;--gp-border:rgba(255,255,255,.12)}
.garna-privacy{position:fixed;inset:0;z-index:2147483000;pointer-events:none;color:var(--gp-ink);font-family:Manrope,ui-sans-serif,system-ui,sans-serif}
.garna-privacy[hidden],.garna-privacy [hidden]{display:none!important}.garna-privacy__shade{position:absolute;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(10px);pointer-events:auto}
.garna-privacy__morph{position:absolute;left:18px;bottom:18px;z-index:1;box-sizing:border-box;overflow:hidden;border:1px solid var(--gp-border);background:rgba(16,17,15,.97);box-shadow:0 28px 90px rgba(0,0,0,.44),0 0 0 1px rgba(203,243,0,.03) inset;pointer-events:auto;transform-origin:left bottom;will-change:width,height,border-radius}
.garna-privacy[data-view=collapsed] .garna-privacy__morph{width:max-content;border-radius:14px}.garna-privacy[data-view=banner] .garna-privacy__morph{width:min(570px,calc(100vw - 36px));border-radius:22px}.garna-privacy[data-view=panel] .garna-privacy__morph{width:min(690px,calc(100vw - 36px));border-radius:24px}
.garna-privacy__banner{box-sizing:border-box;width:100%;padding:26px}.garna-privacy__eyebrow{display:flex;align-items:center;gap:9px;margin:0 0 11px;color:var(--gp-lime);font-size:11px;font-weight:700;letter-spacing:.13em;text-transform:uppercase}.garna-privacy__eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--gp-lime);box-shadow:0 0 0 5px rgba(203,243,0,.1)}
.garna-privacy__title{margin:0;color:#fff;font-size:26px;font-weight:500;line-height:1.13;letter-spacing:-.035em}.garna-privacy__text{margin:13px 0 0;color:var(--gp-muted);font-size:14px;line-height:1.6}.garna-privacy__text a{color:#fff;text-decoration:underline;text-decoration-color:var(--gp-lime);text-underline-offset:4px}
.garna-privacy__actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:22px}.garna-privacy__button{min-height:46px;padding:0 16px;border:1px solid var(--gp-border);border-radius:12px;background:#1a1b18;color:#fff;font:650 13px/1 Manrope,ui-sans-serif,system-ui,sans-serif;cursor:pointer;transition:border-color .18s,background .18s,transform .18s}.garna-privacy__button:hover{border-color:rgba(203,243,0,.65);transform:translateY(-1px)}.garna-privacy__button--primary{border-color:var(--gp-lime);background:var(--gp-lime);color:#10110f}.garna-privacy__button--wide{grid-column:1/-1}
.garna-privacy__button:focus-visible,.garna-privacy-reopen:focus-visible,.garna-privacy__close:focus-visible,.garna-privacy__toggle input:focus-visible+span{outline:3px solid rgba(203,243,0,.38);outline-offset:2px}.garna-privacy__panel{box-sizing:border-box;width:100%;max-height:min(760px,calc(100vh - 36px));overflow:auto;padding:28px}.garna-privacy__panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.garna-privacy__close{width:40px;height:40px;flex:0 0 40px;border:1px solid var(--gp-border);border-radius:50%;background:#1a1b18;color:#fff;font-size:22px;cursor:pointer}
.garna-privacy__categories{display:grid;gap:10px;margin:22px 0}.garna-privacy__category{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:start;padding:16px;border:1px solid var(--gp-border);border-radius:15px;background:rgba(255,255,255,.025)}.garna-privacy__category h3{margin:0;color:#fff;font-size:15px;line-height:1.3}.garna-privacy__category p{margin:6px 0 0;color:var(--gp-muted);font-size:12px;line-height:1.5}
.garna-privacy__toggle{position:relative;display:inline-flex}.garna-privacy__toggle input{position:absolute;width:1px;height:1px;opacity:0}.garna-privacy__toggle span{display:block;width:46px;height:26px;border-radius:999px;background:#454740;cursor:pointer;transition:.18s}.garna-privacy__toggle span:after{content:"";display:block;width:20px;height:20px;margin:3px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.35);transition:.18s}.garna-privacy__toggle input:checked+span{background:var(--gp-lime)}.garna-privacy__toggle input:checked+span:after{transform:translateX(20px);background:#10110f}.garna-privacy__toggle input:disabled+span{opacity:.48;cursor:not-allowed}.garna-privacy__gpc{margin:16px 0 0;padding:12px 14px;border:1px solid rgba(203,243,0,.2);border-radius:12px;background:rgba(203,243,0,.07);color:#dff58b;font-size:12px;line-height:1.5}
.garna-privacy-reopen{display:inline-flex;min-height:42px;align-items:center;gap:10px;padding:0 15px 0 13px;border:0;border-radius:inherit;background:transparent;color:#e7e8e2;font:650 12px/1 Manrope,ui-sans-serif,system-ui,sans-serif;cursor:pointer}.garna-privacy-reopen:before{content:"";width:10px;height:10px;box-sizing:border-box;border:3px solid var(--gp-lime);border-radius:50%;box-shadow:0 0 0 4px rgba(203,243,0,.09)}.garna-privacy-reopen:hover{background:rgba(255,255,255,.04)}
.garna-privacy-embed{display:grid;min-height:240px;place-items:center;padding:24px;border:1px solid var(--gp-border);border-radius:14px;background:#10110f;color:var(--gp-muted);text-align:center}.garna-privacy-embed button{min-height:40px;margin-top:12px;padding:0 15px;border:0;border-radius:10px;background:var(--gp-lime);color:#10110f;font:700 13px/1 inherit;cursor:pointer}
@media(max-width:640px){.garna-privacy__morph{left:8px;bottom:8px}.garna-privacy[data-view=banner] .garna-privacy__morph,.garna-privacy[data-view=panel] .garna-privacy__morph{width:calc(100vw - 16px);border-radius:18px}.garna-privacy__banner,.garna-privacy__panel{padding:20px}.garna-privacy__title{font-size:22px}.garna-privacy__actions{grid-template-columns:1fr}.garna-privacy__button--wide{grid-column:auto}.garna-privacy__panel{max-height:calc(100vh - 16px)}}
@media(prefers-reduced-motion:reduce){.garna-privacy__button,.garna-privacy__toggle span,.garna-privacy__toggle span:after{transition:none}}
</style>`;

export function buildPrivacyManagerSnippet(language = 'en'): string {
	const normalizedLanguage = ['en', 'es', 'pt', 'ru'].includes(language.slice(0, 2).toLowerCase()) ? language.slice(0, 2).toLowerCase() : 'en';
	const script = `(function(){
'use strict';
var COOKIE=${safeJson(PRIVACY_COOKIE_NAME)},VERSION=${PRIVACY_POLICY_VERSION},LANGUAGE=${safeJson(normalizedLanguage)};
var copy={
en:{eyebrow:'Privacy controls',title:'Your privacy, your choice',body:'Necessary technologies keep Garna secure and working. Optional technologies help us understand the site and remember attribution.',ca:'California residents may opt out of sale or sharing. We also honor Global Privacy Control.',accept:'Accept all',reject:'Reject optional',manage:'Customize',save:'Save choices',close:'Close',necessary:'Strictly necessary',necessaryText:'Security, routing, core site functions and storing this privacy choice.',preferences:'Preferences',preferencesText:'Remember optional interface and booking choices.',analytics:'Analytics',analyticsText:'Measure visits and interactions so we can improve the experience.',marketing:'Marketing and attribution',marketingText:'Remember campaign attribution and support future advertising tools.',gpc:'Global Privacy Control is active. Analytics, sale, sharing and marketing remain disabled.',reopen:'Privacy choices',doNotSell:'Do not sell or share',embed:'This external content is disabled until analytics technologies are allowed.',enable:'Review privacy choices',policy:'Privacy Policy'},
es:{eyebrow:'Controles de privacidad',title:'Tu privacidad, tu elección',body:'Las tecnologías necesarias mantienen Garna seguro y en funcionamiento. Las opcionales nos ayudan a entender el sitio y recordar la atribución.',ca:'Los residentes de California pueden excluirse de la venta o el intercambio. También respetamos Global Privacy Control.',accept:'Aceptar todo',reject:'Rechazar opcionales',manage:'Personalizar',save:'Guardar selección',close:'Cerrar',necessary:'Estrictamente necesarias',necessaryText:'Seguridad, enrutamiento, funciones básicas y almacenamiento de esta selección.',preferences:'Preferencias',preferencesText:'Recuerdan opciones de interfaz y reserva.',analytics:'Analítica',analyticsText:'Mide visitas e interacciones para mejorar la experiencia.',marketing:'Marketing y atribución',marketingText:'Recuerda la atribución de campañas y admite futuras herramientas publicitarias.',gpc:'Global Privacy Control está activo. La analítica, venta, intercambio y marketing permanecen desactivados.',reopen:'Opciones de privacidad',doNotSell:'No vender ni compartir',embed:'Este contenido externo está desactivado hasta que permitas tecnologías analíticas.',enable:'Revisar privacidad',policy:'Política de privacidad'},
pt:{eyebrow:'Controlos de privacidade',title:'A sua privacidade, a sua escolha',body:'As tecnologias necessárias mantêm a Garna segura e funcional. As opcionais ajudam-nos a compreender o site e a memorizar a atribuição.',ca:'Os residentes da Califórnia podem recusar a venda ou partilha. Também respeitamos o Global Privacy Control.',accept:'Aceitar tudo',reject:'Rejeitar opcionais',manage:'Personalizar',save:'Guardar escolhas',close:'Fechar',necessary:'Estritamente necessárias',necessaryText:'Segurança, encaminhamento, funções essenciais e armazenamento desta escolha.',preferences:'Preferências',preferencesText:'Memorizam opções de interface e reserva.',analytics:'Análise',analyticsText:'Mede visitas e interações para melhorar a experiência.',marketing:'Marketing e atribuição',marketingText:'Memoriza a atribuição de campanhas e suporta futuras ferramentas publicitárias.',gpc:'O Global Privacy Control está ativo. Análise, venda, partilha e marketing permanecem desativados.',reopen:'Opções de privacidade',doNotSell:'Não vender nem partilhar',embed:'Este conteúdo externo fica desativado até permitir tecnologias analíticas.',enable:'Rever privacidade',policy:'Política de privacidade'},
ru:{eyebrow:'Настройки приватности',title:'Ваша приватность — ваш выбор',body:'Необходимые технологии обеспечивают безопасность и работу Garna. Дополнительные помогают улучшать сайт и сохранять рекламную атрибуцию.',ca:'Жители Калифорнии могут отказаться от продажи или передачи данных. Мы также учитываем Global Privacy Control.',accept:'Разрешить всё',reject:'Отклонить необязательное',manage:'Настроить',save:'Сохранить выбор',close:'Закрыть',necessary:'Строго необходимые',necessaryText:'Безопасность, маршрутизация, основные функции сайта и сохранение этого выбора.',preferences:'Предпочтения',preferencesText:'Запоминают дополнительные настройки интерфейса и бронирования.',analytics:'Аналитика',analyticsText:'Измеряет посещения и взаимодействия, чтобы улучшать сайт.',marketing:'Маркетинг и атрибуция',marketingText:'Сохраняет рекламную атрибуцию и поддерживает будущие рекламные инструменты.',gpc:'Global Privacy Control включён. Аналитика, продажа, передача данных и маркетинг отключены.',reopen:'Настройки приватности',doNotSell:'Не продавать и не передавать',embed:'Внешний контент отключён, пока вы не разрешите аналитические технологии.',enable:'Открыть настройки',policy:'Политика конфиденциальности'}};
var t=copy[LANGUAGE]||copy.en,context=null,saved=null,current=null,lastFocus=null,root=null;
function readCookie(){var prefix=COOKIE+'=',parts=document.cookie.split(';');for(var i=0;i<parts.length;i++){var item=parts[i].trim();if(item.indexOf(prefix)!==0)continue;try{return JSON.parse(decodeURIComponent(item.slice(prefix.length)));}catch(_){return null;}}return null;}
function valid(value){return value&&value.version===VERSION&&typeof value.analytics==='boolean'&&typeof value.marketing==='boolean'&&typeof value.preferences==='boolean';}
function browserGpc(){return navigator.globalPrivacyControl===true;}
function writeCookie(value){var secure=location.protocol==='https:'?'; Secure':'';document.cookie=COOKIE+'='+encodeURIComponent(JSON.stringify(value))+'; Path=/; Max-Age=15552000; SameSite=Lax'+secure;}
function normalize(value){var base=value||context.defaults,choices={necessary:true,preferences:!!base.preferences,analytics:!!base.analytics,marketing:!!base.marketing};if(context.gpc||browserGpc()){choices.analytics=false;choices.marketing=false;}return choices;}
function cleanOptionalStorage(){if(current&&current.marketing)return;try{Object.keys(localStorage).forEach(function(key){if(/^utm_/i.test(key))localStorage.removeItem(key);});}catch(_){}document.cookie.split(';').forEach(function(part){var name=part.split('=')[0].trim();if(/^utm_|^_ga|^_gid|^_gcl|^_fbp/i.test(name))document.cookie=name+'=; Path=/; Max-Age=0; SameSite=Lax';});}
function updateEmbeds(){document.querySelectorAll('iframe[data-garna-privacy-src]').forEach(function(frame){var allowed=current&&current.analytics,holder=frame.parentElement&&frame.parentElement.querySelector('[data-garna-privacy-embed-for]');if(allowed){frame.src=frame.getAttribute('data-garna-privacy-src');frame.hidden=false;if(holder)holder.remove();return;}frame.src='about:blank';frame.hidden=true;if(!holder&&frame.parentElement){holder=document.createElement('div');holder.className='garna-privacy-embed';holder.setAttribute('data-garna-privacy-embed-for','analytics');holder.innerHTML='<div><div>'+t.embed+'</div><button type="button">'+t.enable+'</button></div>';holder.querySelector('button').addEventListener('click',openSettings);frame.parentElement.insertBefore(holder,frame);}});}
function applyChoices(value){current=normalize(value);cleanOptionalStorage();updateEmbeds();window.dispatchEvent(new CustomEvent('garna:privacy-updated',{detail:{profile:context.profile,choices:Object.assign({},current),gpc:context.gpc||browserGpc()}}));}
function persist(value){var state={version:VERSION,profile:context.profile,updatedAt:new Date().toISOString(),gpc:context.gpc||browserGpc(),necessary:true,preferences:!!value.preferences,analytics:!!value.analytics,marketing:!!value.marketing};if(state.gpc){state.analytics=false;state.marketing=false;}writeCookie(state);saved=state;applyChoices(state);setView('collapsed',true);}
function category(id,title,text){return '<article class="garna-privacy__category"><div><h3>'+title+'</h3><p>'+text+'</p></div><label class="garna-privacy__toggle"><input type="checkbox" data-choice="'+id+'" aria-label="'+title+'"><span></span></label></article>';}
function template(){var node=document.createElement('div'),policy='https://app.garna.io/api/documents/privacy?lang='+encodeURIComponent(LANGUAGE);node.className='garna-privacy';node.hidden=true;node.setAttribute('data-garna-privacy-root','');node.innerHTML='<div class="garna-privacy__shade" data-shade hidden></div><div class="garna-privacy__morph" data-morph><button class="garna-privacy-reopen" type="button" data-reopen aria-expanded="false">'+(context.profile==='california'?t.doNotSell:t.reopen)+'</button><section class="garna-privacy__banner" role="dialog" aria-labelledby="garna-privacy-title" hidden><p class="garna-privacy__eyebrow">'+t.eyebrow+'</p><h2 class="garna-privacy__title" id="garna-privacy-title">'+t.title+'</h2><p class="garna-privacy__text">'+t.body+' <span data-ca-copy hidden>'+t.ca+' </span><a href="'+policy+'" target="_blank" rel="noopener noreferrer">'+t.policy+'</a>.</p><div class="garna-privacy__actions"><button class="garna-privacy__button garna-privacy__button--primary" type="button" data-accept>'+t.accept+'</button><button class="garna-privacy__button" type="button" data-reject>'+t.reject+'</button><button class="garna-privacy__button garna-privacy__button--wide" type="button" data-manage>'+t.manage+'</button></div></section><section class="garna-privacy__panel" role="dialog" aria-modal="true" aria-labelledby="garna-privacy-settings-title" hidden><div class="garna-privacy__panel-head"><div><p class="garna-privacy__eyebrow">'+t.eyebrow+'</p><h2 class="garna-privacy__title" id="garna-privacy-settings-title">'+t.manage+'</h2></div><button class="garna-privacy__close" type="button" data-close aria-label="'+t.close+'">×</button></div><p class="garna-privacy__gpc" data-gpc hidden>'+t.gpc+'</p><div class="garna-privacy__categories"><article class="garna-privacy__category"><div><h3>'+t.necessary+'</h3><p>'+t.necessaryText+'</p></div><label class="garna-privacy__toggle"><input type="checkbox" checked disabled aria-label="'+t.necessary+'"><span></span></label></article>'+category('preferences',t.preferences,t.preferencesText)+category('analytics',t.analytics,t.analyticsText)+category('marketing',t.marketing,t.marketingText)+'</div><div class="garna-privacy__actions"><button class="garna-privacy__button garna-privacy__button--primary" type="button" data-save>'+t.save+'</button><button class="garna-privacy__button" type="button" data-reject>'+t.reject+'</button></div></section></div>';document.body.appendChild(node);return node;}
function parts(){return{morph:root.querySelector('[data-morph]'),reopen:root.querySelector('[data-reopen]'),banner:root.querySelector('.garna-privacy__banner'),panel:root.querySelector('.garna-privacy__panel'),shade:root.querySelector('[data-shade]')};}
function reducedMotion(){return !!(window.matchMedia&&window.matchMedia('(prefers-reduced-motion:reduce)').matches);}
function applyView(view){var el=parts();root.dataset.view=view;root.hidden=false;el.reopen.hidden=view!=='collapsed';el.banner.hidden=view!=='banner';el.panel.hidden=view!=='panel';el.shade.hidden=view!=='panel';el.reopen.setAttribute('aria-expanded',view==='collapsed'?'false':'true');}
function setView(view,animate){var el=parts(),before=el.morph.getBoundingClientRect();if(el.morph.getAnimations)el.morph.getAnimations().forEach(function(item){item.cancel();});applyView(view);var after=el.morph.getBoundingClientRect();if(!animate||reducedMotion()||!el.morph.animate)return;var motion=el.morph.animate([{width:before.width+'px',height:before.height+'px'},{width:after.width+'px',height:after.height+'px'}],{duration:view==='collapsed'?360:430,easing:'cubic-bezier(.16,1,.3,1)',fill:'both'});motion.finished.then(function(){motion.cancel();if(view==='collapsed'&&lastFocus&&lastFocus.focus)lastFocus.focus();}).catch(function(){});}
function openSettings(){lastFocus=document.activeElement;var base=saved||current||context.defaults;root.querySelectorAll('[data-choice]').forEach(function(input){input.checked=!!base[input.getAttribute('data-choice')];});var gpc=context.gpc||browserGpc();root.querySelector('[data-gpc]').hidden=!gpc;root.querySelectorAll('[data-choice=analytics],[data-choice=marketing]').forEach(function(input){input.disabled=gpc;if(gpc)input.checked=false;});setView('panel',true);root.querySelector('[data-close]').focus();}
function closeSettings(){setView(saved?'collapsed':'banner',true);}
function bind(){root.addEventListener('click',function(event){var target=event.target.closest('button');if(!target)return;if(target.hasAttribute('data-reopen')||target.hasAttribute('data-manage'))openSettings();else if(target.hasAttribute('data-accept'))persist({preferences:true,analytics:true,marketing:true});else if(target.hasAttribute('data-reject'))persist({preferences:false,analytics:false,marketing:false});else if(target.hasAttribute('data-close'))closeSettings();else if(target.hasAttribute('data-save')){var result={};root.querySelectorAll('[data-choice]').forEach(function(input){result[input.getAttribute('data-choice')]=input.checked;});persist(result);}});root.querySelector('[data-shade]').addEventListener('click',closeSettings);document.addEventListener('keydown',function(event){if(event.key==='Escape'&&!root.querySelector('.garna-privacy__panel').hidden)closeSettings();if(event.key==='Tab'&&!root.querySelector('.garna-privacy__panel').hidden){var items=Array.from(root.querySelectorAll('.garna-privacy__panel button:not([disabled]),.garna-privacy__panel input:not([disabled])')),first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});}
function boot(){root=template();bind();if(context.profile==='california')root.querySelector('[data-ca-copy]').hidden=false;saved=readCookie();if(!valid(saved))saved=null;if(context.requiresOptIn&&saved&&saved.profile!=='strict_opt_in')saved=null;window.garnaPrivacy={open:openSettings,getChoices:function(){return Object.assign({},current);},hasConsent:function(category){return !!(current&&current[category]);},profile:function(){return context.profile;}};applyChoices(saved||context.defaults);setView(saved?'collapsed':'banner',false);}
function init(){fetch('/api/privacy/context',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json'}}).then(function(response){if(!response.ok)throw new Error('privacy context');return response.json();}).catch(function(){return{version:VERSION,profile:'strict_opt_in',requiresOptIn:true,gpc:browserGpc(),defaults:{necessary:true,preferences:false,analytics:false,marketing:false}};}).then(function(value){context=value;if(browserGpc())context.gpc=true;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();});}
init();
})();`;

	return `${PRIVACY_CSS}\n<script ${PRIVACY_MARKER}>${script}</script>`;
}

export function injectPrivacyManager(html: string, language = 'en'): string {
	if (!html || html.includes(`<script ${PRIVACY_MARKER}>`)) return html;
	const snippet = buildPrivacyManagerSnippet(language);
	const preparedHtml = deferConsentManagedEmbeds(html);
	if (/<\/head>/i.test(preparedHtml)) return preparedHtml.replace(/<\/head>/i, `${snippet}\n</head>`);
	if (/<\/body>/i.test(preparedHtml)) return preparedHtml.replace(/<\/body>/i, `${snippet}\n</body>`);
	return `${snippet}\n${preparedHtml}`;
}

export async function injectPrivacyIntoResponse(response: Response, request: Request): Promise<Response> {
	if (request.method === 'HEAD' || !response.headers.get('content-type')?.toLowerCase().includes('text/html')) return response;

	// Site pages are bounded generated documents, so materializing them here is safe and keeps one consent layer for every route.
	const html = await response.text();
	const language = new URL(request.url).pathname.split('/').filter(Boolean)[0] || 'en';
	const headers = new Headers(response.headers);
	headers.delete('content-length');
	return new Response(injectPrivacyManager(html, language), {
		status: response.status,
		statusText: response.statusText,
		headers,
	});
}
